service:
  name: conecto-api-hooks

package:
  individually: true
  excludeDevDependencies: false

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ../../webpack.config.js
    includeModules: false
    packager: 'npm'
  splitStacks:
    perFunction: false
    perType: true
  dotenv:
    basePath: ../../
  staticMapsBucketName: ${self:custom.stage}-static-maps

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  memorySize: 1024
  environment:
    COMPANY_STATS_TABLE: ${file(../database/serverless.yml):custom.companyStatsTableName}
    NOTIFICATIONS_TABLE: ${file(../database/serverless.yml):custom.notificationsTableName}
    COMPANYSCORE_TABLE: ${file(../database/serverless.yml):custom.companyScoreTableName}
    CONTACTSCORE_TABLE: ${file(../database/serverless.yml):custom.contactScoreTableName}
    DEALINFOS_TABLE: ${file(../database/serverless.yml):custom.dealInfosTableName}
    COMPANYADDRESSES_TABLE: ${file(../database/serverless.yml):custom.companyAddressesTableName}
    CONTACTADDRESSASSIGNMENTS_TABLE: ${file(../database/serverless.yml):custom.contactAddressAssignments}
    STATIC_MAPS_BUCKET: ${self:custom.staticMapsBucketName}
    TZ: ${env:TZ}
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-ApiGatewayRestApiRootResourceId
  ContactsCognitoUserPool:
    'Fn::ImportValue': ${self:custom.stage}-ContactsCognitoUserPool
  iamRoleStatements: ${file(../contacts/serverless.yml):provider.iamRoleStatements}

functions:

  on-new-deal:
    handler: handler.onNewDeal
    timeout: 30
    environment:
      USER_POOL: ${self:provider.ContactsCognitoUserPool}
    events:
      - http:
          method: post
          path: hooks/on-new-deal
          cors:
            origin: '*' # Must stay * for Zapier

  manual-new-deal:
    handler: handler.manualNewDeal
    timeout: 30
    environment:
      USER_POOL: ${self:provider.ContactsCognitoUserPool}
    events:
      - http:
          method: post
          path: hooks/manual-new-deal
          cors:
            origin: '*' # Must stay * for Zapier