Resources:
  CompanyAddressesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # Generate a name based on the stage
      TableName: ${self:custom.companyAddressesTableName}
      AttributeDefinitions:
        - AttributeName: companyId
          AttributeType: N
        - AttributeName: addressId
          AttributeType: S
      KeySchema:
        - AttributeName: companyId
          KeyType: HASH
        - AttributeName: addressId
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

Outputs:
  CompanyAddressesTableArn:
    Value:
      Fn::GetAtt:
        - CompanyAddressesTable
        - Arn
    Export:
      Name: ${self:custom.stage}-CompanyAddressesTableArn