Resources:
  ContactScoreTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # Generate a name based on the stage
      TableName: ${self:custom.contactScoreTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: companyId
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: companyId
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

Outputs:
  ContactScoreTableArn:
    Value:
      Fn::GetAtt:
        - ContactScoreTable
        - Arn
    Export:
      Name: ${self:custom.stage}-ContactScoreTableArn