Resources:
  NotificationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # Generate a name based on the stage
      TableName: ${self:custom.notificationsTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

Outputs:
  NotificationsTableArn:
    Value:
      Fn::GetAtt:
        - NotificationsTable
        - Arn
    Export:
      Name: ${self:custom.stage}-NotificationsTableArn